#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SulpHur")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertUIContents(UIContents instance);
    partial void UpdateUIContents(UIContents instance);
    partial void DeleteUIContents(UIContents instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ConsoleApplication2.Properties.Settings.Default.SulpHurConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UIContents> UIContents
		{
			get
			{
				return this.GetTable<UIContents>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UIContents")]
	public partial class UIContents : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ContentID;
		
		private System.Nullable<System.Guid> _GUID;
		
		private int _ClientID;
		
		private int _BuildID;
		
		private string _UIName;
		
		private System.Xml.Linq.XElement _UIContent;
		
		private System.Data.Linq.Binary _UIScreenShot;
		
		private bool _IsWebUI;
		
		private System.DateTime _DateUploaded;
		
		private System.Nullable<int> _TraceID;
		
		private System.Nullable<int> _Reserve1;
		
		private string _Reserve2;
		
		private string _Reserve3;
		
		private string _Reserve4;
		
		private string _Reserve5;
		
		private string _LaunchedFrom;
		
		private string _WindowHierarchy;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnContentIDChanging(int value);
    partial void OnContentIDChanged();
    partial void OnGUIDChanging(System.Nullable<System.Guid> value);
    partial void OnGUIDChanged();
    partial void OnClientIDChanging(int value);
    partial void OnClientIDChanged();
    partial void OnBuildIDChanging(int value);
    partial void OnBuildIDChanged();
    partial void OnUINameChanging(string value);
    partial void OnUINameChanged();
    partial void OnUIContentChanging(System.Xml.Linq.XElement value);
    partial void OnUIContentChanged();
    partial void OnUIScreenShotChanging(System.Data.Linq.Binary value);
    partial void OnUIScreenShotChanged();
    partial void OnIsWebUIChanging(bool value);
    partial void OnIsWebUIChanged();
    partial void OnDateUploadedChanging(System.DateTime value);
    partial void OnDateUploadedChanged();
    partial void OnTraceIDChanging(System.Nullable<int> value);
    partial void OnTraceIDChanged();
    partial void OnReserve1Changing(System.Nullable<int> value);
    partial void OnReserve1Changed();
    partial void OnReserve2Changing(string value);
    partial void OnReserve2Changed();
    partial void OnReserve3Changing(string value);
    partial void OnReserve3Changed();
    partial void OnReserve4Changing(string value);
    partial void OnReserve4Changed();
    partial void OnReserve5Changing(string value);
    partial void OnReserve5Changed();
    partial void OnLaunchedFromChanging(string value);
    partial void OnLaunchedFromChanged();
    partial void OnWindowHierarchyChanging(string value);
    partial void OnWindowHierarchyChanged();
    #endregion
		
		public UIContents()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ContentID
		{
			get
			{
				return this._ContentID;
			}
			set
			{
				if ((this._ContentID != value))
				{
					this.OnContentIDChanging(value);
					this.SendPropertyChanging();
					this._ContentID = value;
					this.SendPropertyChanged("ContentID");
					this.OnContentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClientID", DbType="Int NOT NULL")]
		public int ClientID
		{
			get
			{
				return this._ClientID;
			}
			set
			{
				if ((this._ClientID != value))
				{
					this.OnClientIDChanging(value);
					this.SendPropertyChanging();
					this._ClientID = value;
					this.SendPropertyChanged("ClientID");
					this.OnClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuildID", DbType="Int NOT NULL")]
		public int BuildID
		{
			get
			{
				return this._BuildID;
			}
			set
			{
				if ((this._BuildID != value))
				{
					this.OnBuildIDChanging(value);
					this.SendPropertyChanging();
					this._BuildID = value;
					this.SendPropertyChanged("BuildID");
					this.OnBuildIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIName", DbType="NVarChar(MAX)")]
		public string UIName
		{
			get
			{
				return this._UIName;
			}
			set
			{
				if ((this._UIName != value))
				{
					this.OnUINameChanging(value);
					this.SendPropertyChanging();
					this._UIName = value;
					this.SendPropertyChanged("UIName");
					this.OnUINameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIContent", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement UIContent
		{
			get
			{
				return this._UIContent;
			}
			set
			{
				if ((this._UIContent != value))
				{
					this.OnUIContentChanging(value);
					this.SendPropertyChanging();
					this._UIContent = value;
					this.SendPropertyChanged("UIContent");
					this.OnUIContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UIScreenShot", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary UIScreenShot
		{
			get
			{
				return this._UIScreenShot;
			}
			set
			{
				if ((this._UIScreenShot != value))
				{
					this.OnUIScreenShotChanging(value);
					this.SendPropertyChanging();
					this._UIScreenShot = value;
					this.SendPropertyChanged("UIScreenShot");
					this.OnUIScreenShotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWebUI", DbType="Bit NOT NULL")]
		public bool IsWebUI
		{
			get
			{
				return this._IsWebUI;
			}
			set
			{
				if ((this._IsWebUI != value))
				{
					this.OnIsWebUIChanging(value);
					this.SendPropertyChanging();
					this._IsWebUI = value;
					this.SendPropertyChanged("IsWebUI");
					this.OnIsWebUIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUploaded", DbType="DateTime NOT NULL")]
		public System.DateTime DateUploaded
		{
			get
			{
				return this._DateUploaded;
			}
			set
			{
				if ((this._DateUploaded != value))
				{
					this.OnDateUploadedChanging(value);
					this.SendPropertyChanging();
					this._DateUploaded = value;
					this.SendPropertyChanged("DateUploaded");
					this.OnDateUploadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TraceID", DbType="Int")]
		public System.Nullable<int> TraceID
		{
			get
			{
				return this._TraceID;
			}
			set
			{
				if ((this._TraceID != value))
				{
					this.OnTraceIDChanging(value);
					this.SendPropertyChanging();
					this._TraceID = value;
					this.SendPropertyChanged("TraceID");
					this.OnTraceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserve1", DbType="Int")]
		public System.Nullable<int> Reserve1
		{
			get
			{
				return this._Reserve1;
			}
			set
			{
				if ((this._Reserve1 != value))
				{
					this.OnReserve1Changing(value);
					this.SendPropertyChanging();
					this._Reserve1 = value;
					this.SendPropertyChanged("Reserve1");
					this.OnReserve1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserve2", DbType="NVarChar(MAX)")]
		public string Reserve2
		{
			get
			{
				return this._Reserve2;
			}
			set
			{
				if ((this._Reserve2 != value))
				{
					this.OnReserve2Changing(value);
					this.SendPropertyChanging();
					this._Reserve2 = value;
					this.SendPropertyChanged("Reserve2");
					this.OnReserve2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserve3", DbType="NVarChar(MAX)")]
		public string Reserve3
		{
			get
			{
				return this._Reserve3;
			}
			set
			{
				if ((this._Reserve3 != value))
				{
					this.OnReserve3Changing(value);
					this.SendPropertyChanging();
					this._Reserve3 = value;
					this.SendPropertyChanged("Reserve3");
					this.OnReserve3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserve4", DbType="NVarChar(MAX)")]
		public string Reserve4
		{
			get
			{
				return this._Reserve4;
			}
			set
			{
				if ((this._Reserve4 != value))
				{
					this.OnReserve4Changing(value);
					this.SendPropertyChanging();
					this._Reserve4 = value;
					this.SendPropertyChanged("Reserve4");
					this.OnReserve4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserve5", DbType="NVarChar(MAX)")]
		public string Reserve5
		{
			get
			{
				return this._Reserve5;
			}
			set
			{
				if ((this._Reserve5 != value))
				{
					this.OnReserve5Changing(value);
					this.SendPropertyChanging();
					this._Reserve5 = value;
					this.SendPropertyChanged("Reserve5");
					this.OnReserve5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaunchedFrom", DbType="NVarChar(1000)")]
		public string LaunchedFrom
		{
			get
			{
				return this._LaunchedFrom;
			}
			set
			{
				if ((this._LaunchedFrom != value))
				{
					this.OnLaunchedFromChanging(value);
					this.SendPropertyChanging();
					this._LaunchedFrom = value;
					this.SendPropertyChanged("LaunchedFrom");
					this.OnLaunchedFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WindowHierarchy", DbType="NVarChar(MAX)")]
		public string WindowHierarchy
		{
			get
			{
				return this._WindowHierarchy;
			}
			set
			{
				if ((this._WindowHierarchy != value))
				{
					this.OnWindowHierarchyChanging(value);
					this.SendPropertyChanging();
					this._WindowHierarchy = value;
					this.SendPropertyChanged("WindowHierarchy");
					this.OnWindowHierarchyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
